# Generated by Django 5.0.2 on 2025-01-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_status', models.CharField(choices=[('EMAIL_NOT_CONFIGURED', 'EMAIL_NOT_CONFIGURED'), ('EMAIL_NOT_SENT', 'EMAIL_NOT_SENT'), ('EMAIL_SENDING', 'EMAIL_SENDING'), ('EMAIL_SENT', 'EMAIL_SENT'), ('EMAIL_SENDING_FAILED', 'EMAIL_SENDING_FAILED')], default='EMAIL_NOT_CONFIGURED', max_length=30)),
                ('asset_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(max_length=255)),
                ('notification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
    ]
