# Generated by Django 5.0.2 on 2025-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10)),
                ('email', models.EmailField(default='experion@experion.com', max_length=100, null=True, unique=True, verbose_name='email address')),
                ('mobile_phone', models.CharField(max_length=20, null=True)),
                ('employee_department', models.CharField(max_length=100, null=True)),
                ('employee_designation', models.CharField(max_length=50, null=True)),
                ('office_location', models.CharField(max_length=50, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
