# Generated by Django 5.0.2 on 2025-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10, null=True)),
                ('object_id', models.CharField(max_length=36)),
                ('email', models.EmailField(default='experion@experion.com', max_length=100, null=True, unique=True, verbose_name='email address')),
                ('mobile_phone', models.CharField(max_length=60, null=True)),
                ('employee_department', models.CharField(max_length=100, null=True)),
                ('employee_designation', models.CharField(max_length=100, null=True)),
                ('office_location', models.CharField(max_length=50, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_source', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('additional_data', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
