# Generated by Django 5.0.2 on 2025-01-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSyncHistory',
        ),
    ]
