# Generated by Django 5.0.2 on 2025-01-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_delete_employeesynchistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_source', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('additional_data', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
