[global]
hostname = "http://localhost:5173"
login_endpoint = "/login"
dashboard_endpoint = "/exam/dashboard"


[sso]
redirect_url = "http://localhost:5173/sso/flow?refresh_token={}&access_token={}"

# TODO Should show the callback uris to be used for different IdPs

[employee]
data_source = "AZURE_AD"
scopes = ['https://graph.microsoft.com/.default']
refresh_interval_seconds = 900


[dummy_data]
asset_id = ["DUMMY-01234", "DUMMY-11234"]
asset_category = "SOFTWARE"

asset_type = "Docker"
product_name = "Docker 2024"
model_number = "DUMMY-1234"
owner = "EXPERION"
status = "SCRAP"
warranty_period = 24
license_type = ["Permanent", "Monthly"]
is_deleted = true

location = "Trivandrum"
business_unit = "DU1"
memory = 16

[dummy_data.custodian]
name = "ams_employee"
department = "DU1"
designation = ""

[dummy_data.user.lead]
username = "AMS1"
password = "password"
email = "ams1@ams.com"
user_scope = "LEAD"

[dummy_data.user.system_admin]
username = "AMS2"
password = "password"
email = "ams2@ams.com"
user_scope = "SYSTEM_ADMIN"


[import]
import_batch_size = 1000

# TODO The below is not currently used in code
[model_data]

[model_data.asset]
asset_category = ["HARDWARE", "SOFTWARE"]
default_asset_owner = "EXPERION"

[model_data.asset.status.asset_status]
asset_status = ["STOCK", "USE", "DAMAGED", "REPAIR", "OUTDATED", "SCRAP"]
default_asset_status = "STOCK"
asset_status_in_which_asset_is_in_use = "USE"
asset_status_in_which_asset_is_in_stock = "STOCK"

asset_status_in_which_asset_not_assignable = [
    "DAMAGED",
    "OUTDATED",
    "REPAIR",
    "SCRAP",
]

[model_data.user.application]
# User scopes used by application
user_scopes = ["MANAGER", "LEAD", "SYSTEM_ADMIN"]
user_scope_manager = "MANAGER"
user_scope_lead = "LEAD"
user_scope_sysadmin = "SYSTEM_ADMIN"

[model_data.user.client]
# User scopes used by the client
user_scope_manager = ["MANAGER"]
user_scope_lead = ["LEAD", "SENIORLEAD"]
user_scope_sysadmin = ["SYSTEM_ADMIN", "SYSADMIN", "SENIORADMINISTRATOR"]
