# Generated by Django 5.0.2 on 2024-02-22 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "request_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ASSET CREATION", "Asset Creation"),
                            ("ASSET ASSIGNMENT", "Asset Assignment"),
                            ("ASSET STATUS UPDATE", "Asset Status Update"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_description", models.TextField()),
                ("reject_description", models.TextField()),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DELETE", "Delete"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "asset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="asset.asset"
                    ),
                ),
                (
                    "conceder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceder_user",
                        to="asset.user",
                    ),
                ),
                (
                    "requester_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_user",
                        to="asset.user",
                    ),
                ),
            ],
        ),
    ]
