# Generated by Django 5.0.2 on 2024-02-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="asset_id",
            new_name="asset",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="conceder_id",
            new_name="conceder",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="requester_id",
            new_name="requester",
        ),
    ]
