# Generated by Django 5.0.2 on 2024-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_rename_asset_id_request_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="request_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
