# Generated by Django 5.0.2 on 2024-02-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0003_alter_request_request_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="reject_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
