export const statusColors: { [key: string]: string } = {
    "IN STORE": "#FFB92A",
    "IN REPAIR": "#FEEB51",
    "IN USE": "#9BCA3E",
    "IN SERVICE": "#3ABBC9",
    DISPOSED: "#3ABBC9",
    EXPIRED: "#CC0000",
    UNASSIGNED: "#E6E6E6",
    ASSIGN_PENDING: "#FFB92A",
    ASSIGNED: "#9BCA3E",
    REJECTED: "#CC0000",
    CREATE_PENDING: "#FD6A02",
    UPDATE_PENDING: "#FD6A02",
    CREATED: "#9BCA3E",
    UPDATED: "#3ABBC9",
    CREATE_REJECTED: "#CC0000",
    UPDATE_REJECTED: "#CC0000",
    PENDING: "#FFB92A",
  };