export const statusMapping: { [key: string]: string } = {
  UNASSIGNED: "UNASSIGNED",
  ASSIGN_PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  REJECTED: "REJECTED",
  CREATE_PENDING: "PENDING",
  UPDATE_PENDING: "PENDING",
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  CREATE_REJECTED: "REJECTED",
  UPDATE_REJECTED: "REJECTED",
  "IN STORE": "STOCK",
  EXPIRED:"INACTIVE",
  SCRAP: "SCRAP",
  "IN USE": "ALLOCATED"
};