# Generated by Django 5.0.2 on 2024-02-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessunit",
            old_name="bu_id",
            new_name="bu_uuid",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="employee_id",
            new_name="employee_uuid",
        ),
        migrations.RenameField(
            model_name="memory",
            old_name="memory_id",
            new_name="memory_uuid",
        ),
    ]
