# Generated by Django 5.0.2 on 2024-02-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='asset_tpe_name',
            new_name='asset_type_name',
        ),
    ]
