# Generated by Django 5.0.2 on 2024-05-15 12:16
 
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ("asset", "0001_initial"),
    ]
 
    operations = [
        migrations.AddField(
            model_name="asset",
            name="LicenseType",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
 