# Generated by Django 5.0.2 on 2024-02-19 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessunit",
            old_name="bu_id",
            new_name="bu_uuid",
        ),
        migrations.RenameField(
            model_name="memory",
            old_name="memory_id",
            new_name="memory_uuid",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_id",
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
