# Generated by Django 5.0.2 on 2024-02-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_uuid']},
        ),
    ]
