# Generated by Django 5.0.2 on 2024-03-05 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="conceder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_conceder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("ASSIGN", "ASSIGN"),
                    ("UPDATE", "UPDATE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="requester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
