# Generated by Django 5.0.2 on 2024-02-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_rename_bu_id_businessunit_bu_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(default='employee', on_delete=django.db.models.deletion.CASCADE, to='asset.assettype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(default='employee', on_delete=django.db.models.deletion.CASCADE, to='asset.businessunit'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='custodian',
            field=models.ForeignKey(default='employee', on_delete=django.db.models.deletion.CASCADE, related_name='assets_custodian', to='asset.employee'),
        ),
    ]
