# Generated by Django 5.0.2 on 2024-05-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_asset_licensetype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="LicenseType",
            new_name="license_type",
        ),
    ]
