# Generated by Django 5.0.2 on 2024-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_rename_asset_tpe_name_assettype_asset_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlog',
            name='processor_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
