# Generated by Django 5.0.2 on 2024-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_assetlog_processor_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='processor_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
