# Generated by Django 5.0.2 on 2024-05-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_rename_licensetype_asset_license_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="business_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="asset.businessunit",
            ),
        ),
    ]
