# Generated by Django 5.0.2 on 2024-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_alter_asset_conceder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("ASSIGN", "ASSIGN"),
                    ("UPDATE", "UPDATE"),
                ],
                max_length=50,
            ),
        ),
    ]
