# Generated by Django 5.0.2 on 2024-02-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_asset_type_alter_asset_business_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='custodian',
        ),
    ]
