# Generated by Django 5.0.2 on 2024-06-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='accessories',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
