# Generated by Django 5.0.2 on 2024-02-19 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_remove_asset_asset_type_remove_asset_business_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
