# Generated by Django 5.0.2 on 2024-02-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_alter_employee_employee_uuid"),
        ("asset", "0005_user"),
    ]

    operations = []
