# Generated by Django 5.0.2 on 2024-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0006_alter_asset_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="owner",
            field=models.CharField(default="EXPERION", max_length=50),
        ),
    ]
