# Generated by Django 5.0.2 on 2024-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0007_alter_asset_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="os",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
